-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 05:45:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotecadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bibliotecadb` ;

-- -----------------------------------------------------
-- Schema bibliotecadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecadb` DEFAULT CHARACTER SET utf8 ;
USE `bibliotecadb` ;

-- -----------------------------------------------------
-- Table `bibliotecadb`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecadb`.`Autor` ;

CREATE TABLE IF NOT EXISTS `bibliotecadb`.`Autor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NULL,
  `nascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecadb`.`Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecadb`.`Livro` ;

CREATE TABLE IF NOT EXISTS `bibliotecadb`.`Livro` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `isbn` VARCHAR(13) NULL,
  `publicacao` YEAR NULL,
  `editora` VARCHAR(50) NULL,
  `genero` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecadb`.`AutorEscreveLivro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecadb`.`AutorEscreveLivro` ;

CREATE TABLE IF NOT EXISTS `bibliotecadb`.`AutorEscreveLivro` (
  `autorid` INT NOT NULL,
  `livroid` INT NOT NULL,
  PRIMARY KEY (`autorid`, `livroid`),
  INDEX `fk_Autor_has_Livro_Livro1_idx` (`livroid` ASC) VISIBLE,
  INDEX `fk_Autor_has_Livro_Autor_idx` (`autorid` ASC) VISIBLE,
  CONSTRAINT `fk_Autor_has_Livro_Autor`
    FOREIGN KEY (`autorid`)
    REFERENCES `bibliotecadb`.`Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Livro_Livro1`
    FOREIGN KEY (`livroid`)
    REFERENCES `bibliotecadb`.`Livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecadb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecadb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `bibliotecadb`.`Usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(80) NOT NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` VARCHAR(100) NULL,
  `tipo` ENUM('Aluno', 'Professor') NULL,
  `cadastro` TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecadb`.`Exemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecadb`.`Exemplar` ;

CREATE TABLE IF NOT EXISTS `bibliotecadb`.`Exemplar` (
  `id` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `observacao` TEXT NULL,
  `Livro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Exemplar_Livro1_idx` (`Livro_id` ASC) VISIBLE,
  CONSTRAINT `fk_Exemplar_Livro1`
    FOREIGN KEY (`Livro_id`)
    REFERENCES `bibliotecadb`.`Livro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecadb`.`emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecadb`.`emprestimo` ;

CREATE TABLE IF NOT EXISTS `bibliotecadb`.`emprestimo` (
  `id` INT NOT NULL,
  `emprestimo` TIMESTAMP(3) NOT NULL,
  `dovulucao` DATE NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprestimo_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `bibliotecadb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecadb`.`emprestimo_has_Exemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bibliotecadb`.`emprestimo_has_Exemplar` ;

CREATE TABLE IF NOT EXISTS `bibliotecadb`.`emprestimo_has_Exemplar` (
  `emprestimo_id` INT NOT NULL,
  `Exemplar_id` INT NOT NULL,
  PRIMARY KEY (`emprestimo_id`, `Exemplar_id`),
  INDEX `fk_emprestimo_has_Exemplar_Exemplar1_idx` (`Exemplar_id` ASC) VISIBLE,
  INDEX `fk_emprestimo_has_Exemplar_emprestimo1_idx` (`emprestimo_id` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_has_Exemplar_emprestimo1`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `bibliotecadb`.`emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_has_Exemplar_Exemplar1`
    FOREIGN KEY (`Exemplar_id`)
    REFERENCES `bibliotecadb`.`Exemplar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
